name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Cut a Release

    runs-on: ubuntu-latest

    permissions:
      contents: write # needed for creating the release
      id-token: write

    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        activate-environment: true

    - name: Set up Python
      run: uv python install

    - name: Build
      id: build
      run: |
        uv sync --group=build
        uv run -m build
        twine check --strict dist/*

    - name: Publish on PyPI
      id: publish
      uses: pypa/gh-action-pypi-publish@release/v1

    - name: Set Tag
      id: set-tag
      run: |
        echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Create release
      id: create-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.tag }}
      run: |
        gh release create "$tag" \
            --title="PicoFun ${tag}" \
            --generate-notes

    - name: Upload Assets
      id: upload-assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.tag }}
      run: |
        gh release upload $tag dist/*.whl dist/*.tar.gz